<template>
                <ele-multi-cascader
                    :options="list"
                    v-model="form.isp"
                    placeholder="请选择范围"
                    @change="ispChange"
                    ref="cascader"
                    show-all-levels
                    output-level-value
                    selectChildren
                    labelKey="name"
                    valueKey="key"
                    childrenKey="children"
                    :panelWidth="'auto'"
                  >
                </ele-multi-cascader>
</template>

<script>


export default {
  name: 'select-program-property',
  props:{
    propLabel:String,
    propProp:String
  },
  data() {
    return {
      list: [
        {
          key:'programBasic',
          name:'项目基本信息',
          children:[
            {
              key:'program_source',
              name:'项目来源',
              children:null
            },
            {
              key:'type',
              name:'类型',
              children:null
            },
            {
              key:'ref',
              name:'参考基线',
              children:null
            },
            {
              key:'state',
              name:'项目状态',
              children:null
            },
            {
              key:'classification',
              name:'密级',
              children:null
            },
            {
              key:'name',
              name:'项目名称',
              children:null
            },
            {
              key:'model',
              name:'所属型号',
              children:null
            },
            {
              key:'program_type',
              name:'测试类型',
              children:null
            },
            {
              key:'program_identity',
              name:'项目标识',
              children:null
            },
            {
              key:'program_stage',
              name:'项目阶段',
              children:null
            },
            {
              key:'dev_type',
              name:'研制类型',
              children:null
            },
            {
              key:'plan_start_time',
              name:'计划开始时间',
              children:null
            },
            {
              key:'plan_end_time',
              name:'计划结束时间',
              children:null
            },
            {
              key:'actual_start_time',
              name:'实际开始时间',
              children:null
            },
            {
              key:'actual_end_time',
              name:'实际结束时间',
              children:null
            },
            {
              key:'manager',
              name:'型号负责人',
              children:null
            }
          ]
        },
        {
          key:'contact',
          name:'联系人',
          children:[
            {
              key:'plan',
              name:'计划',
              children:null
            },
            {
              key:'quality',
              name:'质量',
              children:null
            },
            {
              key:'code',
              name:'设计',
              children:null
            }
            ]
        },
         {
          key:'softwareInfo',
          name:'软件信息',
          children:[
            {
              key:'software_name',
              name:'软件名称',
              children:null
            },
            {
              key:'version_id',
              name:'版本号',
              children:null
            },
            {
              key:'reduced_code_size',
              name:'折算后代码',
              children:null
            },
            {
              key:'reduced_reason',
              name:'折算原因',
              children:null
            },
            {
              key:'software_type',
              name:'软件类型',
              children:null
            },
            {
              key:'software_usage',
              name:'软件用途',
              children:null
            },
            {
              key:'code_langu',
              name:'编程语言',
              children:null
            },
            {
              key:'complier',
              name:'编译器',
              children:null
            },
            {
              key:'runtime',
              name:'运行环境',
              children:null
            },
            {
              key:'cpu_type',
              name:'CPU类型',
              children:null
            },
             {
              key:'software_cate',
              name:'被测软件类型',
              children:null
            },
            {
              key:'software_sub_cate',
              name:'被测软件子类',
              children:null
            }
          ]
        },
        {
          key:'workflow',
          name:'流程信息',
          children:[
            {
              key:'workflow_state',
              name:'当前节点',
              children:null
            },
            {
              key:'issue',
              name:'当前节点问题',
              children:null
            }
          ]
        },
        {
          key:'programTeamRole',
          name:'项目组信息',
          children:[
            {
              key:'program_leader',
              name:'项目组长',
              children:null
            },
            {
              key:'program_team_strict',
              name:'项目组员',
              children:null
            }
          ]
        }
        ],
      form: {
          isp: []
      },
      key_list:null
    }
  },

   methods: {
    ispChange(values, items) {
      this.key_list=values.filter(x=>x.includes('/')).map(x=>x.slice(x.indexOf('/')+1));
      this.$emit('rangeChange',this.key_list);
    }
  }

}
</script>

<style scoped>
</style>


